<div class="fieldset">
    <div class="checkbox">
        <div class="col-sm-9 col-sm-offset-3">

            <label>
                <input type="hidden"  name="<?php echo $this->getFieldName('invoice_email')?>" value="0" >
                <input type="checkbox"
                       name="<?php echo $this->getFieldName('invoice_email')?>"
                       id="<?php echo $this->getFieldId('invoice_email')?>"
                       value="1"
                       <?php if($this->getCustomer()->getInvoiceEmail()) : ?>checked="checked"<?php endif; ?>
                       title="<?php echo $this->__('Switch on invoice mails') ?>"
                       class="checkbox" />
                <?php echo $this->__('Switch on invoice mails') ?>
            </label>
        </div>
    </div>
</div>
